#!/bin/sh

set -e

not_installed() {
    ! command -v $1 > /dev/null 2>&1
}

bitbucket_pull_request_resource_dir="$(cd $(dirname $0)/.. && pwd)"

if not_installed ginkgo; then
    echo "# ginkgo is not installed! run the following command:"
    echo "    go install github.com/onsi/ginkgo/ginkgo"
    exit 1
fi

cd "$bitbucket_pull_request_resource_dir"
ginkgo -p -r
